export type MemberRole = "owner" | "admin" | "member" | "advisor"
export type StartupStage = "idea" | "validation" | "mvp" | "early_revenue" | "growth" | "scale"
export type OnboardingStatus = "not_started" | "in_progress" | "completed"
export type ProjectStatus = "draft" | "active" | "paused" | "archived"
export type MessageRole = "user" | "assistant" | "system"
export type DocumentStatus = "pending" | "processing" | "ready" | "failed"
export type InsightStatus = "queued" | "processing" | "completed" | "failed"

type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
type Timestamps = { created_at: string; updated_at: string }

export interface Database {
  public: {
    Tables: {
      profiles: { Row: Timestamps & { id: string; full_name: string | null; avatar_url: string | null; phone: string | null; country_code: string | null; city: string | null; timezone: string; last_active_at: string | null }; Insert: Partial<Omit<Database["public"]["Tables"]["profiles"]["Row"], "id" | "created_at" | "updated_at">> & { id: string }; Update: Partial<Omit<Database["public"]["Tables"]["profiles"]["Row"], "id" | "created_at">>; Relationships: [] }
      startups: { Row: Timestamps & { id: string; owner_id: string; name: string; slug: string; country_code: string; city: string | null; industry: string | null; stage: StartupStage; estimated_budget_cents: number | null; budget_currency: string; website_url: string | null; description: string | null; onboarding_status: OnboardingStatus; onboarding_completed_at: string | null }; Insert: Omit<Database["public"]["Tables"]["startups"]["Row"], "id" | "created_at" | "updated_at" | "stage" | "budget_currency" | "onboarding_status" | "onboarding_completed_at"> & Partial<Pick<Database["public"]["Tables"]["startups"]["Row"], "id" | "stage" | "budget_currency" | "onboarding_status" | "onboarding_completed_at">>; Update: Partial<Omit<Database["public"]["Tables"]["startups"]["Row"], "id" | "owner_id" | "created_at">>; Relationships: [] }
      startup_members: { Row: { startup_id: string; user_id: string; role: MemberRole; invited_by: string | null; joined_at: string }; Insert: Omit<Database["public"]["Tables"]["startup_members"]["Row"], "joined_at"> & Partial<Pick<Database["public"]["Tables"]["startup_members"]["Row"], "joined_at">>; Update: Partial<Pick<Database["public"]["Tables"]["startup_members"]["Row"], "role" | "invited_by">>; Relationships: [] }
      projects: { Row: Timestamps & { id: string; startup_id: string; created_by: string; title: string; description: string | null; target_audience: string | null; status: ProjectStatus; metadata: Json }; Insert: Omit<Database["public"]["Tables"]["projects"]["Row"], "id" | "created_at" | "updated_at" | "status" | "metadata"> & Partial<Pick<Database["public"]["Tables"]["projects"]["Row"], "id" | "status" | "metadata">>; Update: Partial<Omit<Database["public"]["Tables"]["projects"]["Row"], "id" | "startup_id" | "created_by" | "created_at">>; Relationships: [] }
      ai_configurations: { Row: Timestamps & { id: string; project_id: string; primary_use_case: string; tone_of_voice: string; model: string | null; system_instructions: string | null; settings: Json; created_by: string }; Insert: Omit<Database["public"]["Tables"]["ai_configurations"]["Row"], "id" | "created_at" | "updated_at" | "model" | "system_instructions" | "settings"> & Partial<Pick<Database["public"]["Tables"]["ai_configurations"]["Row"], "id" | "model" | "system_instructions" | "settings">>; Update: Partial<Omit<Database["public"]["Tables"]["ai_configurations"]["Row"], "id" | "project_id" | "created_by" | "created_at">>; Relationships: [] }
      knowledge_documents: { Row: Timestamps & { id: string; startup_id: string; project_id: string | null; uploaded_by: string; file_name: string; storage_path: string; mime_type: string | null; size_bytes: number | null; status: DocumentStatus; extracted_text: string | null; metadata: Json }; Insert: Omit<Database["public"]["Tables"]["knowledge_documents"]["Row"], "id" | "created_at" | "updated_at" | "project_id" | "mime_type" | "size_bytes" | "status" | "extracted_text" | "metadata"> & Partial<Pick<Database["public"]["Tables"]["knowledge_documents"]["Row"], "id" | "project_id" | "mime_type" | "size_bytes" | "status" | "extracted_text" | "metadata">>; Update: Partial<Omit<Database["public"]["Tables"]["knowledge_documents"]["Row"], "id" | "startup_id" | "uploaded_by" | "created_at">>; Relationships: [] }
      conversations: { Row: Timestamps & { id: string; startup_id: string; project_id: string | null; created_by: string; title: string | null; archived_at: string | null }; Insert: Omit<Database["public"]["Tables"]["conversations"]["Row"], "id" | "created_at" | "updated_at" | "project_id" | "title" | "archived_at"> & Partial<Pick<Database["public"]["Tables"]["conversations"]["Row"], "id" | "project_id" | "title" | "archived_at">>; Update: Partial<Omit<Database["public"]["Tables"]["conversations"]["Row"], "id" | "startup_id" | "created_by" | "created_at">>; Relationships: [] }
      messages: { Row: { id: string; conversation_id: string; author_id: string | null; role: MessageRole; content: string; model: string | null; token_count: number | null; metadata: Json; created_at: string }; Insert: Omit<Database["public"]["Tables"]["messages"]["Row"], "id" | "created_at" | "author_id" | "model" | "token_count" | "metadata"> & Partial<Pick<Database["public"]["Tables"]["messages"]["Row"], "id" | "author_id" | "model" | "token_count" | "metadata">>; Update: never; Relationships: [] }
      insights: { Row: { id: string; startup_id: string; project_id: string | null; requested_by: string; kind: string; title: string; status: InsightStatus; input: Json; result: Json | null; error_message: string | null; created_at: string; completed_at: string | null }; Insert: Omit<Database["public"]["Tables"]["insights"]["Row"], "id" | "created_at" | "project_id" | "status" | "input" | "result" | "error_message" | "completed_at"> & Partial<Pick<Database["public"]["Tables"]["insights"]["Row"], "id" | "project_id" | "status" | "input" | "result" | "error_message" | "completed_at">>; Update: Partial<Omit<Database["public"]["Tables"]["insights"]["Row"], "id" | "startup_id" | "requested_by" | "kind" | "created_at">>; Relationships: [] }
      usage_events: { Row: { id: number; startup_id: string | null; user_id: string | null; event_name: string; quantity: number; metadata: Json; occurred_at: string }; Insert: Omit<Database["public"]["Tables"]["usage_events"]["Row"], "id" | "quantity" | "metadata" | "occurred_at"> & Partial<Pick<Database["public"]["Tables"]["usage_events"]["Row"], "quantity" | "metadata" | "occurred_at">>; Update: never; Relationships: [] }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: { member_role: MemberRole; startup_stage: StartupStage; onboarding_status: OnboardingStatus; project_status: ProjectStatus; message_role: MessageRole; document_status: DocumentStatus; insight_status: InsightStatus }
    CompositeTypes: Record<string, never>
  }
}
