/**
 * Provenance labels so founders never confuse AI estimates with measured reality.
 * - tracked: entered by the founder or imported from a real system
 * - projected: generated by AI as a forecast / scenario
 * - derived: computed from existing app records (tasks, docs) — not live market data
 */
export type DataProvenance = "tracked" | "projected" | "derived"

export const PROVENANCE_LABEL: Record<DataProvenance, string> = {
  tracked: "Tracked",
  projected: "AI projection",
  derived: "Derived",
}

export const PROVENANCE_HINT: Record<DataProvenance, string> = {
  tracked: "Numbers you entered or imported — not AI fiction.",
  projected: "Scenario forecast from AI. Not live product analytics.",
  derived: "Calculated from tasks, documents, and workspace activity in this app.",
}

export interface TrackedMetrics {
  updatedAt: string
  monthlyRevenue: number
  currency: string
  activeCustomers: number
  monthlyBurn: number
  visitorsThisMonth: number
  notes?: string
}

export function emptyTrackedMetrics(currency = "USD"): TrackedMetrics {
  return {
    updatedAt: "",
    monthlyRevenue: 0,
    currency,
    activeCustomers: 0,
    monthlyBurn: 0,
    visitorsThisMonth: 0,
  }
}

export function hasTrackedMetrics(metrics: TrackedMetrics | null | undefined): boolean {
  if (!metrics?.updatedAt) return false
  return (
    metrics.monthlyRevenue > 0 ||
    metrics.activeCustomers > 0 ||
    metrics.monthlyBurn > 0 ||
    metrics.visitorsThisMonth > 0
  )
}

export function runwayMonths(metrics: TrackedMetrics | null | undefined): number | null {
  if (!metrics || metrics.monthlyBurn <= 0) return null
  // Rough cash runway if burn is known; revenue reduces net burn
  const netBurn = Math.max(0, metrics.monthlyBurn - metrics.monthlyRevenue)
  if (netBurn <= 0) return null
  // Without cash balance we only signal burn pressure — callers should not invent runway cash
  return null
}

export function netMonthlyBurn(metrics: TrackedMetrics): number {
  return Math.max(0, metrics.monthlyBurn - metrics.monthlyRevenue)
}

export function readMetadata(raw: unknown): Record<string, unknown> {
  return raw && typeof raw === "object" && !Array.isArray(raw) ? (raw as Record<string, unknown>) : {}
}

export function readTrackedMetrics(metadata: Record<string, unknown>, currency = "USD"): TrackedMetrics {
  const raw = metadata.tracked_metrics
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return emptyTrackedMetrics(currency)
  }
  const m = raw as Partial<TrackedMetrics>
  return {
    updatedAt: typeof m.updatedAt === "string" ? m.updatedAt : "",
    monthlyRevenue: Number(m.monthlyRevenue) || 0,
    currency: typeof m.currency === "string" ? m.currency : currency,
    activeCustomers: Number(m.activeCustomers) || 0,
    monthlyBurn: Number(m.monthlyBurn) || 0,
    visitorsThisMonth: Number(m.visitorsThisMonth) || 0,
    notes: typeof m.notes === "string" ? m.notes : undefined,
  }
}

export interface AnalyticsWorkspaceSnapshot {
  source: "projected"
  generatedAt: string
  kpis: unknown[]
  funnel: unknown[]
  channels: unknown[]
  history: unknown[]
  recommendations: { title: string; detail: string }[]
}

/** Normalize legacy workspaces that were incorrectly labeled "tracked". */
export function normalizeAnalyticsWorkspace(raw: unknown): AnalyticsWorkspaceSnapshot | null {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null
  const ws = raw as Record<string, unknown>
  if (!ws.kpis || !ws.funnel || !ws.channels || !ws.history) return null
  return {
    ...(ws as unknown as AnalyticsWorkspaceSnapshot),
    source: "projected",
  }
}

export interface PersistedMarketingEvent {
  id: string
  day: number
  label: string
  color: string
  content?: string
  createdAt: string
}

export interface MarketingWorkspaceData {
  events: PersistedMarketingEvent[]
  updatedAt: string
}

export function readMarketingWorkspace(metadata: Record<string, unknown>): MarketingWorkspaceData {
  const raw = metadata.marketing_workspace
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    return { events: [], updatedAt: "" }
  }
  const ws = raw as Partial<MarketingWorkspaceData>
  const events = Array.isArray(ws.events)
    ? ws.events.filter(
        (e): e is PersistedMarketingEvent =>
          !!e &&
          typeof e === "object" &&
          typeof (e as PersistedMarketingEvent).id === "string" &&
          typeof (e as PersistedMarketingEvent).label === "string",
      )
    : []
  return {
    events,
    updatedAt: typeof ws.updatedAt === "string" ? ws.updatedAt : "",
  }
}
